genres = [
    ('Action and Adventure','Action and Adventure'),
    ('Alternate History','Alternate History'),
    ('Anthology','Anthology'),
    ('Chick Lit','Chick Lit'),
    ('Children','Children'),
    ('Classic','Classic'),
    ('Comic Book','Comic Book'),
    ('Coming-of-Age','Coming-of-Age'),
    ('Crime','Crime'),
    ('Drama','Drama'),
    ('Fairytale','Fairytale'),
    ('Fantasy','Fantasy'),
    ('Graphic Novel','Graphic Novel'),
    ('Historical Fiction','Historical Fiction'),
    ('Horror','Horror'),
    ('Mystery','Mystery'),
    ('Paranormal Romance','Paranormal Romance'),
    ('Picture Book','Picture Book'),
    ('Poetry','Poetry'),
    ('Political Thriller','Political Thriller'),
    ('Romance','Romance'),
    ('Satire','Satire'),
    ('Science Fiction','Science Fiction'),
    ('Short Story','Short Story'),
    ('Suspense','Suspense'),
    ('Thriller','Thriller'),
    ('Western','Western'),
    ('Young Adult','Young Adult'),
    ('Art and Architecture','Art and Architecture'),
    ('Autobiography','Autobiography'),
    ('Biography','Biography'),
    ('Business and Economics','Business and Economics'),
    ('Crafts and Hobbies','Crafts and Hobbies'),
    ('Cookbook','Cookbook'),
    ('Diary','Diary'),
    ('Dictionary','Dictionary'),
    ('Encyclopedia','Encyclopedia'),
    ('Guide','Guide'),
    ('Health and Fitness','Health and Fitness'),
    ('History','History'),
    ('Home and Garden','Home and Garden'),
    ('Humor','Humor'),
    ('Journal','Journal'),
    ('Math','Math'),
    ('Memoir','Memoir'),
    ('Philosophy','Philosophy'),
    ('Prayer','Prayer'),
    ('Religion and Spirituality','Religion and Spirituality'),
    ('New Age','New Age'),
    ('Textbook','Textbook'),
    ('True Crime','True Crime'),
    ('Review','Review'),
    ('Science','Science'),
    ('Self Help','Self Help'),
    ('Sports and Leisure','Sports and Leisure'),
    ('Travel','Travel'),
    ('True Crime', 'True Crime')
]
